### ISSUE TITLE
Heroku Error on creating relations on deploy command

### ISSUE THREAD

**Issue by dcfwight** [miguelgrinberg/flasky-first-edition#3]
Hi, I'm finishing the Flasky first edition book - I think it's excellent!
I'm having a problem in the last bit though - deploying to Heroku.
The app is working fine in the local environment. I've also triple checked all my code to the github for Flaksy 1 and also had a look at the github for Flasky 2 edition and the Flask Mega Tutorial for clues as to where I'm going wrong and can't see any.

The code is uploaded to Heroku fine, all the packages from requirements are loaded, and the application starts.
But then I try to run the deploy code
`heroku python manage.py deploy`

I get the error message:
"psycopg2.errors.UndefinedTable: relation "roles" does not exist"

So, have I set up my database incorrectly? I've looked at models.py very closely compared with yours and can't see any difference, especially w.r.t. Roles and Users. The database is also working fine under a local server.

Full traceback is pasted below. Any tips or hints, or how I can start the database afresh?
Thanks, Doug.

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e16ed9da28b5, Add index to Role
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_context
    self.dialect.do_execute(
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "roles" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 82, in <module>
    manager.run()
  File "/app/.heroku/python/lib/python3.9/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/app/.heroku/python/lib/python3.9/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/app/.heroku/python/lib/python3.9/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/app/manage.py", line 72, in deploy
    upgrade()
  File "/app/.heroku/python/lib/python3.9/site-packages/flask_migrate/__init__.py", line 247, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/util/compat.py", line 63, in load_module_py
    return machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 90, in <module>
    run_migrations_online()
  File "migrations/env.py", line 84, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/app/migrations/versions/e16ed9da28b5_add_index_to_role.py", line 21, in upgrade
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
  File "<string>", line 8, in create_index
  File "<string>", line 3, in create_index
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/operations/ops.py", line 857, in create_index
    return operations.invoke(op)
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 88, in create_index
    operations.impl.create_index(idx)
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/ddl/impl.py", line 206, in create_index
    self._exec(schema.CreateIndex(index))
  File "/app/.heroku/python/lib/python3.9/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 997, in _execute_ddl
    ret = self._execute_context(
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1184, in _execute_context
    self._handle_dbapi_exception(
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1400, in _handle_dbapi_exception
    util.raise_from_cause(
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_context
    self.dialect.do_execute(
  File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "roles" does not exist
 [SQL: 'CREATE UNIQUE INDEX ix_roles_name ON roles (name)']

**Comment by miguelgrinberg** [comment]
Do you have the roles table in one of your database migrations? If yes, are you calling `flask db upgrade` to get the migrations to run?

**Comment by dcfwight** [comment]
I now see the problem - you are right, in my migrations/versions folder there is no migrate file which creates the Role('roles') and User('users') tables.
From cross-referencing to your github, I can see these were done in the very first migrate command.
I've checked all the others, and after that missing step, all the other migrates are present in my folder structure.

So I must have made a mistake in the very first db migrate / db upgrade task.
[I'm not sure how I could have done this and still have a correctly operating database under local server?]

My question now is how to fix it? Presumably I can't just copy and paste your migrate code for the initial migration into my folder structure, because I assume they are all linked in a chain? If I'm missing that first link, is there a way of comparing my final 'complete' database structure to 'blank' structure and running db migrate on that?
Many thanks for your help.
Doug.

**Comment by miguelgrinberg** [comment]
The most common cause for this mistake is that the migration is created, and applied, and then at some point in the future inadvertently deleted.

The migrations are linked by their SHA identifier, with each migration script pointing to the previous one. You can insert the missing migration and then fix the SHA of the second migration so that it points to it, and then everything should be correct. You can verify that your migration history is correct by running `flask db history`.

**Comment by dcfwight** [comment]
Thanks for your really quick response - very much appreciated.

1. I suspect you are right - I probably did delete that file without knowing what I was doing.
2. I did as you suggested, inspected my migrate files and inserted the original migrate file and matched the SHA ids to make the chain work - worked perfectly.
3. I then took a while for heroku to accept my version of psycopg2 - it refused to unpack versions 2.51, 2.6, 2.73, but eventually worked with 2.86 (and gunicorn v 20.1.0)
4. After those changes - everything working perfectly on heroku - thanks!

One final question - I'm confident that the database is working fine, because it is serving over the internet without error, and also I can query it through
`heroku run python manage.py shell`

But how would i run your suggestion of `flask db history` through heroku? I've tried `
heroku run flask db history` 
and also 
`heroku run python flask db history` 
and finally trying 
`heroku run python manage.py shell` then various commands in the shell, but none of them give any meaningful output.

Thanks again for your help.

**Comment by miguelgrinberg** [comment]
Oh, okay, sorry, I gave you the commands that apply to recent versions of Flask and the 2nd edition of the book. With the 1st edition you would run `python manage.py db history`.

**Comment by dcfwight** [comment]
Ah, got it, thanks.
Yes, on running `heroku python manage.py db history` it gives the following output pasted below, which looks correct based on the migrate files. I guess it would output an error if there was an issue.
Do I mark this issue closed, or do you?
Thx, Doug.

66a5b4fda2fb -> 038a1e936ff5 (head), Create Comment Class
ecc9e841ef63 -> 66a5b4fda2fb, Add Follow table for followers
32c85fa6dba0 -> ecc9e841ef63, Add gravatar_has
3742914c9f4a -> 32c85fa6dba0, Add html to posts
c737e89e339a -> 3742914c9f4a, Add post class
9102d07b1f58 -> c737e89e339a, Add fields to User
9c05c5e60e8d -> 9102d07b1f58, empty message
6266116f53ad -> 9c05c5e60e8d, Add confirmed email column
38c4e85512a9 -> 6266116f53ad, empty message
<base> -> 38c4e85512a9, initial migration
Revision ID: 38c4e85512a9
Revises: None
Create Date: 2013-12-27 01:23:59.392801

**Comment by miguelgrinberg** [comment]
Yes, that looks good. You would see errors, or more than one head migration if the sequence was wrong. You can close it if you are happy that the issue is resolved, or else my bot will eventually get to it and close it due to inactivity.

**Comment by dcfwight** [comment]
Great, thanks.
